version: "3.10"
networks:
  SpeedTest:
    name: SpeedTest
    driver: bridge
services:
  pure-php:
    image: daalvand/speed-test-pure-php
    container_name: SpeedTestPurePHP
    networks:
      - SpeedTest
    restart: unless-stopped
  swoole-php:
    image: daalvand/speed-test-swoole-php
    container_name: SpeedTestSwoolePHP
    networks:
      - SpeedTest
    restart: unless-stopped
  react-php:
    image: daalvand/speed-test-react-php
    container_name: SpeedTestReactPHP
    networks:
      - SpeedTest
    restart: unless-stopped
  laravel:
    image: daalvand/speed-test-laravel
    container_name: SpeedTestLaravel
    networks:
      - SpeedTest
    restart: unless-stopped
  laravel-octane:
    image: daalvand/speed-test-laravel-octane
    container_name: SpeedTestLaravelOctane
    networks:
      - SpeedTest
    restart: unless-stopped
  yii:
    image: daalvand/speed-test-yii
    container_name: SpeedTestYii
    networks:
      - SpeedTest
    restart: unless-stopped
  codeigniter:
    image: daalvand/speed-test-codeigniter
    container_name: SpeedTestCodeigniter
    networks:
      - SpeedTest
    restart: unless-stopped
  nodejs:
    image: daalvand/speed-test-nodejs
    container_name: SpeedTestNodeJS
    restart: unless-stopped
    networks:
      - SpeedTest
  go:
    image: daalvand/speed-test-go
    container_name: SpeedTestGO
    restart: unless-stopped
    networks:
      - SpeedTest
  flask:
    image: daalvand/speed-test-flask
    container_name: SpeedTestFlask
    restart: unless-stopped
    networks:
      - SpeedTest
  fastapi:
    image: daalvand/speed-test-fastapi
    container_name: SpeedTestFastAPI
    restart: unless-stopped
    networks:
      - SpeedTest
  base:
    image: daalvand/speed-test-base
    container_name: SpeedTestBase
    networks:
      - SpeedTest
    profiles:
      - donotstart
  plt:
    image: daalvand/speed-test-plt
    container_name: SpeedTestPLT
    networks:
      - SpeedTest
    profiles:
      - donotstart
