version: "3.10"
networks:
  SpeedTest:
    name: SpeedTest
    driver: bridge
services:
  pure-php:
    image: daalvand/speed-test-pure-php
    container_name: SpeedTestPurePHP
    networks:
      - SpeedTest
    restart: unless-stopped
  swoole-php:
    image: daalvand/speed-test-swoole-php
    container_name: SpeedTestSwoolePHP
    networks:
      - SpeedTest
    restart: unless-stopped
  react-php:
    image: daalvand/speed-test-react-php
    container_name: SpeedTestReactPHP
    working_dir: /app
    networks:
      - SpeedTest
    restart: unless-stopped
  laravel:
    image: daalvand/speed-test-laravel
    container_name: SpeedTestLaravel
    networks:
      - SpeedTest
    restart: unless-stopped
  laravel-octane:
    image: daalvand/speed-test-laravel-octane
    container_name: SpeedTestLaravelOctane
    networks:
      - SpeedTest
    restart: unless-stopped
  yii:
    image: daalvand/php:8.2-swoole-fpm-alpine
    container_name: SpeedTestYii
    working_dir: /app
    networks:
      - SpeedTest
    restart: unless-stopped
  codeigniter:
    image: daalvand/speed-test-codeigniter
    container_name: SpeedTestCodeigniter
    networks:
      - SpeedTest
    restart: unless-stopped
  nodejs:
    image: daalvand/speed-test-node
    container_name: SpeedTestNodeJS
    restart: unless-stopped
    networks:
      - SpeedTest
  go:
    image: daalvand/speed-test-go
    container_name: SpeedTestGO
    restart: unless-stopped
    networks:
      - SpeedTest
  flask:
    image: daalvand/speed-test-flask
    container_name: SpeedTestFlask
    working_dir: /app
    restart: unless-stopped
    networks:
      - SpeedTest
  fastapi:
    image: daalvand/speed-test-fastapi
    container_name: SpeedTestFastAPI
    working_dir: /app
    restart: unless-stopped
    networks:
      - SpeedTest
  ab:
    image: daalvand/speed-test-base
    container_name: SpeedTestAB
    networks:
      - SpeedTest
    entrypoint:
      - ab
    profiles:
      - donotstart
  wrk:
    image: daalvand/speed-test-base
    container_name: SpeedTestWRK
    networks:
      - SpeedTest
    entrypoint:
      - wrk
    profiles:
      - donotstart
  hey:
    image: daalvand/speed-test-base
    container_name: SpeedTestHEY
    networks:
      - SpeedTest
    entrypoint:
      - hey
    profiles:
      - donotstart
  plt:
    image: daalvand/speed-test-plt
    container_name: SpeedTestPLT
    networks:
      - SpeedTest
    profiles:
      - donotstart
