version: "3.10"
networks:
  SpeedTest:
    name: SpeedTest
    driver: bridge
services:
  pure-php:
    build:
      context: .
      dockerfile: PHPDockerfile
    container_name: SpeedTestPurePHP
    working_dir: /app
    networks:
      - SpeedTest
    expose:
      - "80"
    volumes:
      - ./services/pure-php:/app
    restart: unless-stopped
    command: [ 'php', '-S', '0.0.0.0:80' ]
  swoole-php:
    build:
      context: .
      dockerfile: PHPDockerfile
    container_name: SpeedTestSwoolePHP
    working_dir: /app
    expose:
      - "80"
    networks:
      - SpeedTest
    volumes:
      - ./services/swoole-php:/app
    restart: unless-stopped
    command: [ 'php', 'index.php' ]
  react-php:
    build:
      context: .
      dockerfile: PHPDockerfile
    container_name: SpeedTestReactPHP
    working_dir: /app
    networks:
      - SpeedTest
    expose:
      - "80"
    volumes:
      - ./services/react-php:/app
    restart: unless-stopped
    command: [ 'php', 'index.php' ]
  laravel:
    build:
      context: .
      dockerfile: PHPDockerfile
    container_name: SpeedTestLaravel
    working_dir: /app
    networks:
      - SpeedTest
    expose:
      - "80"
    volumes:
      - ./services/laravel:/app
    restart: unless-stopped
    command: [ 'php', 'artisan', 'serve', '--host=0.0.0.0', '--port=80' ]
  laravel-octane:
    build:
      context: .
      dockerfile: PHPDockerfile
    container_name: SpeedTestLaravelOctane
    working_dir: /app
    networks:
      - SpeedTest
    expose:
      - "80"
    volumes:
      - ./services/laravel:/app
    restart: unless-stopped
    command: [ 'php', 'artisan', 'octane:start', '--host=0.0.0.0', '--port=80' ]
  yii:
    build:
      context: .
      dockerfile: PHPDockerfile
    container_name: SpeedTestYii
    working_dir: /app
    networks:
      - SpeedTest
    expose:
      - "80"
    volumes:
      - ./services/yii:/app
    restart: unless-stopped
    command: [ 'php', 'yii', 'serve', '0.0.0.0', '--port=80' ]
  nodejs:
    image: node:18
    container_name: SpeedTestNodeJS
    working_dir: /app
    expose:
      - "80"
    volumes:
      - ./services/nodejs:/app
    restart: unless-stopped
    command: [ 'node', 'index.js' ]
    networks:
      - SpeedTest
  go:
    image: golang:1.20.6
    container_name: SpeedTestGO
    working_dir: /app
    expose:
      - "80"
    volumes:
      - ./services/go:/app
    restart: unless-stopped
    command: [ 'go', 'run', 'index.go' ]
    networks:
      - SpeedTest
  flask:
    build:
      context: .
      dockerfile: PythonDockerfile
    container_name: SpeedTestFlask
    working_dir: /app
    expose:
      - "80"
    volumes:
      - ./services/flask:/app
    restart: unless-stopped
    command: ['python', 'index.py']
    networks:
      - SpeedTest
  fastapi:
    build:
      context: .
      dockerfile: PythonDockerfile
    container_name: SpeedTestFastAPI
    working_dir: /app
    expose:
      - "80"
    volumes:
      - ./services/fastapi:/app
    restart: unless-stopped
    command: ['uvicorn', 'index:app',  '--reload', '--host', '0.0.0.0', '--port', '80']
    networks:
      - SpeedTest
  ab:
    build:
      dockerfile: AlpineDockerfile
    container_name: SpeedTestAB
    networks:
      - SpeedTest
    entrypoint:
      - ab
    profiles:
      - donotstart
  wrk:
    build:
      dockerfile: AlpineDockerfile
    container_name: SpeedTestWRK
    networks:
      - SpeedTest
    entrypoint:
      - wrk
    profiles:
      - donotstart
