name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push base
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-base:latest
      - name: Build and push plt
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:plt"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-plt:latest
      - name: Build and push pure php
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:services/pure-php"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-pure-php:latest
      - name: Build and push react php
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:services/react-php"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-react-php:latest
      - name: Build and push swoole php
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:services/swoole-php"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-swoole-php:latest
      - name: Build and push yii
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:services/yii"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-yii:latest
      - name: Build and push codeigniter
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:services/codeigniter"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-codeigniter:latest
      - name: Build and push laravel
        uses: docker/build-push-action@v4
        with:
          file: FPMDockerfile
          context: "{{defaultContext}}:services/laravel"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-laravel:latest
      - name: Build and push laravel octane
        uses: docker/build-push-action@v4
        with:
          file: SwooleDockerfile
          context: "{{defaultContext}}:services/laravel"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-laravel-octane:latest
      - name: Build and push go
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:services/go"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-go:latest
      - name: Build and push fastapi
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:services/fastapi"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-fastapi:latest
      - name: Build and push flask
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:services/flask"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-flask:latest
      - name: Build and push nodejs
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:services/nodejs"
          push: ${{ github.event_name != 'pull_request' }}
          tags: daalvand/speed-test-nodejs:latest
